OG_SLN/Controllers/MsgController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OG_SLN.Models;
using PagedList;
using System.Data.Objects;

namespace OG_SLN.Controllers
{
    public class MsgController : Controller
    {
        private OGDBEntities db = new OGDBEntities();

        //
        // GET: /Msg/

        public ActionResult Index(string sortOrder, string CurrentSort, int? page)
        {
            //var trn_msg = db.TRN_MSG;
            //return View(trn_msg.ToList());

            int pageSize = 10;
            int pageIndex = 1;

            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;

            IPagedList<TRN_MSG> msg = null;
            MessageSearchViewModel messageModel = null;

            var messages = db.TRN_MSG.AsQueryable();

            if (Request.QueryString.HasKeys() && !page.HasValue)
            {
                messageModel = new MessageSearchViewModel();

                if (!string.IsNullOrEmpty(Request.QueryString["Search_From_User"]))
                {
                    messageModel.Search_From_User = decimal.Parse(Request.QueryString["Search_From_User"]);
                    messages = messages.Where(u => u.FROM_USER_NO == messageModel.Search_From_User);
                }
                /*
                if (!string.IsNullOrEmpty(Request.QueryString["Search_To_User"]))
                {
                    messageModel.Search_To_User = decimal.Parse(Request.QueryString["Search_To_User"]);
                    messages = messages.Where(u => u.FROM_USER_NO == messageModel.Search_To_User);
                }
                */
                if (!string.IsNullOrEmpty(Request.QueryString["Search_Subject"]))
                {
                    messageModel.Search_Subject = Request.QueryString["Search_Subject"];
                    messages = messages.Where(u => u.MSG_SUBJECT.ToLower()
                        .Contains(messageModel.Search_Subject.ToLower()));
                }
                if (!string.IsNullOrEmpty(Request.QueryString["Search_Date_From"]))
                {
                    messageModel.Search_Date_From = DateTime.Parse(Request.QueryString["Search_Date_From"]);
                    messages = messages.Where(u => u.INSERT_TIME >= messageModel.Search_Date_From);
                }
                if (!string.IsNullOrEmpty(Request.QueryString["Search_Date_To"]))
                {
                    messageModel.Search_Date_To = DateTime.Parse(Request.QueryString["Search_Date_To"]);
                    messages = messages.Where(u => u.INSERT_TIME <= messageModel.Search_Date_To);
                }
                

                Session["Message_Search_Model"] = messageModel;
            }

            if (!Request.QueryString.HasKeys() && !page.HasValue)
            {
                Session["Message_Search_Model"] = null;
            }

            if (Session["Message_Search_Model"] != null)
            {
                messageModel = (MessageSearchViewModel)Session["Message_Search_Model"];

                if (messageModel.Search_From_User.HasValue)
                {
                    messages = messages.Where(u => u.FROM_USER_NO == messageModel.Search_From_User);
                }
                /*
                if (messageModel.Search_To_User.HasValue)
                {
                    messages = messages.Where(u => u.FROM_USER_NO == messageModel.Search_To_User);
                }
                */
                if (!string.IsNullOrEmpty(messageModel.Search_Subject))
                {
                    messages = messages.Where(u => u.MSG_SUBJECT.ToLower()
                        .Contains(messageModel.Search_Subject.ToLower()));
                }

                if (messageModel.Search_Date_From.HasValue)
                {
                    messages = messages.Where(u => u.INSERT_TIME >= messageModel.Search_Date_From);
                }

                if (messageModel.Search_Date_To.HasValue)
                {
                    messages = messages.Where(u => u.INSERT_TIME <= messageModel.Search_Date_To);
                }
            }

            msg = messages.OrderBy(m => m.INSERT_TIME)
                            .ToPagedList(pageIndex, pageSize);

            ViewBag.Search_Message_Model = (MessageSearchViewModel)Session["Message_Search_Model"];

            return View(msg);
        }

        //
        // GET: /Msg/Details/5

        public ActionResult Details(decimal id = 0)
        {
            TRN_MSG trn_msg = db.TRN_MSG.Single(t => t.MSG_NO == id);
            if (trn_msg == null)
            {
                return HttpNotFound();
            }
            return View(trn_msg);
        }

        //
        // GET: /Msg/Create

        public ActionResult Create()
        {
            ViewBag.REF_MSG_NO = new SelectList(db.TRN_MSG, "MSG_NO", "LAST_ACTION");
            return View();
        }

        //
        // POST: /Msg/Create

        [HttpPost]
        public ActionResult Create(TRN_MSG msg)
        {
            if (ModelState.IsValid)
            {
                decimal? USER_NO = Session["sess_USER_NO"] as decimal?;
                decimal? LOGON_NO = Session["sess_LOGON_NO"] as decimal?;

                //db.TRN_MSG.AddObject(trn_msg);
                //db.SaveChanges();

                decimal? msg_no = db.TRN_MSG_INSERT(USER_NO, LOGON_NO, USER_NO, msg.MSG_SUBJECT, msg.MSG_BODY,
                    null, null, null, null).FirstOrDefault().Value;

                foreach (ZonalManagerViewModel manager in msg.ZonalManagers)
                {
                    db.TRN_MSG_RECIEVER_INSERT(USER_NO, LOGON_NO, msg_no, manager.USER_NO);
                }

                return RedirectToAction("Index");
            }

            ViewBag.REF_MSG_NO = new SelectList(db.TRN_MSG, "MSG_NO", "LAST_ACTION", msg.REF_MSG_NO);
            ViewBag.ZONAL_USER_NO = new SelectList(db.SEC_USERS
                .Where(u => u.USER_TYPE_NO == (decimal)EUserTypes.ZonalManager), "USER_NO", "USER_FULL_NAME");

            return View(msg);
        }

        //
        // GET: /Msg/Edit/5

        public ActionResult Edit(decimal id = 0)
        {
            TRN_MSG trn_msg = db.TRN_MSG.Single(t => t.MSG_NO == id);
            if (trn_msg == null)
            {
                return HttpNotFound();
            }
            ViewBag.REF_MSG_NO = new SelectList(db.TRN_MSG, "MSG_NO", "LAST_ACTION", trn_msg.REF_MSG_NO);
            return View(trn_msg);
        }

        //
        // POST: /Msg/Edit/5

        [HttpPost]
        public ActionResult Edit(TRN_MSG trn_msg)
        {
            if (ModelState.IsValid)
            {
                db.TRN_MSG.Attach(trn_msg);
                db.ObjectStateManager.ChangeObjectState(trn_msg, EntityState.Modified);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.REF_MSG_NO = new SelectList(db.TRN_MSG, "MSG_NO", "LAST_ACTION", trn_msg.REF_MSG_NO);
            return View(trn_msg);
        }

        //
        // GET: /Msg/Delete/5

        public ActionResult Delete(decimal id = 0)
        {
            TRN_MSG trn_msg = db.TRN_MSG.Single(t => t.MSG_NO == id);
            if (trn_msg == null)
            {
                return HttpNotFound();
            }
            return View(trn_msg);
        }

        //
        // POST: /Msg/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(decimal id)
        {
            TRN_MSG trn_msg = db.TRN_MSG.Single(t => t.MSG_NO == id);
            db.TRN_MSG.DeleteObject(trn_msg);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

OG_SLN/Views/Msg/Create.cshtml
@model OG_SLN.TRN_MSG

@using OG_SLN.Helpers

@{
    ViewBag.Title = "New Message";
}

<script type="text/javascript" language="javascript">
    var zonalcount = 0;
    $(function () {
        $('.dialogLink').removeClass('dialogLink').addClass('dialogLinkMultiple');

        $('.dialogLinkMultiple').live('click', function () {
            var element = $(this);

            // Retrieve values from the HTML5 data attributes of the link
            var dialogTitle = element.attr('data-dialog-title');
            var updateTargetId = '#' + element.attr('data-update-target-id');
            var updateUrl = element.attr('data-update-url');

            var dialogDiv = "<div></div>";

            // Load the form into the dialog div
            $(dialogDiv).load(this.href, function () {
                $(this).dialog({
                    modal: true,
                    resizable: true,
                    height: 600,
                    width: 550,
                    title: dialogTitle,

                    buttons: {
                        "Get Selected": function () {
                            var zonals = $('#zonal_result input[type=checkbox]:checked');

                            var resultdiv = $('#zonalselected');
                            if (zonals.length > 0 && zonalcount == 0) {
                                $(resultdiv).append('<tr><th>Full Name</th><th>HR ID</th><th>Mobile</th><th>Email</th></tr>');
                            }
                            $.each(zonals, function (i, zonal) {
                                var parent = $(zonal).parent().parent();
                                var zonalno = $(parent).find('input[name="ZonalManagers.Index"]').val();

                                var exists = $('#zonalselected').find('input[name="ZonalManagers[' + zonalno + '].USER_NO"]');

                                if (exists.length == 0) {
                                    var removed = $(parent).find('.check').remove();

                                    $(resultdiv).append('<tr>' + $(parent).html()
                                        + '<td><a class="delete btn btn-danger" href="#">Delete</a></td></tr>');
                                    zonalcount++;
                                }
                            });

                            //$(this).dialog('close');
                            $(this).remove();
                        }
                    },

                    close: function (event, ui) {
                        //$(this).dialog('destroy');
                        $(this).remove();
                    }
                });
            });
            return false;
        });

        $('.delete').live('click', function () {
            $(this).parent().parent().remove();
        });

        $('.selectall').live('click', function () {
            $('#zonal_result input[type=checkbox]').prop('checked', true);
        });

        $('.unselectall').live('click', function () {
            $('#zonal_result input[type=checkbox]').prop('checked', false);
        });
    });

    function verify() {
        if (confirm("Do you really want to send this message?")) {
            return true;
        }
        return false;
    }
</script>

<h2>New Message</h2>

 @using (Html.BeginForm(ViewContext.RouteData.GetRequiredString("action"), ViewContext.RouteData.GetRequiredString("Controller"), FormMethod.Post, new { @class = "form-horizontal" }))
 {
    @Html.ValidationSummary(true)
    <div class="col-6 col-sm-6 col-lg-10 marRight_2">
   
        <legend>Send New Message</legend>
        <table class="tabWidth">
        <tr class="success2">
               <td>
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-5 control-label">
                        Zonal Manager
                        @Html.Hidden("USER_NO", "")
                        @Html.Hidden("ZONAL_TYPE", "multi")
                    </label>
                    <div class="col-sm-5">
                        @Html.ZonalManagerDialogFormLink("Select", Url.Action("ZonalManager", "ViewDCRSheet"), "Select Zonal Manager")
                        @Html.ValidationMessageFor(model => model.REF_MSG_NO)
                    </div>
                </div>
               
               </td>
            </tr>
            <tr>
                <td colspan="2">
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-3 control-label">
                            @Html.LabelFor(model => model.MSG_SUBJECT)
                        </label>
                        <div class="col-sm-9">
                            @Html.TextBoxFor(model => model.MSG_SUBJECT, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.MSG_SUBJECT)
                        </div>
                     </div>
                </td>
                <td></td>
                
            </tr>
            <tr>
                <td colspan="2">
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-3 control-label">
                            @Html.LabelFor(model => model.MSG_BODY_ML)
                        </label>
                        <div class="col-sm-9">
                            @Html.EditorFor(model => model.MSG_BODY_ML, new { @Class = "form-control" })
                            @Html.ValidationMessageFor(model => model.MSG_BODY_ML)
                        </div>
                    </div>
                </td>
                <td></td>
            </tr>

            @*<tr class="success2">
               <td>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-5 control-label">
                            @Html.LabelFor(model => model.REF_MSG_NO, "TRN_MSG2")
                        </label>
                        <div class="col-sm-5">
                            @Html.DropDownList("REF_MSG_NO", String.Empty)
                            @Html.ValidationMessageFor(model => model.REF_MSG_NO)
                        </div>
                    </div>
               </td>
            </tr>*@

            
            <tr><table class="table table-responsive" id="zonalselected">
                </table></tr>
            <tr><td colspan="3">&nbsp;</td></tr>
            <tr>  
                <td colspan="3" style="text-align:center">
                    <input class="btn btn-success" type="submit" name="Search" id="Search" value="Send Message" onclick="verify();">
                </td>
            </tr>
       </table>
    
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { }, new { @class="btn btn-primary"})
</div>

OG_SLN/Views/Msg/Delete.cshtml
@model OG_SLN.TRN_MSG

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>TRN_MSG</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LAST_ACTION)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LAST_ACTION)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LAST_ACTION_TIME)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LAST_ACTION_TIME)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LAST_ACTION_USER_NO)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LAST_ACTION_USER_NO)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LAST_ACTION_LOGON_NO)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LAST_ACTION_LOGON_NO)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.INSERT_TIME)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.INSERT_TIME)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.INSERT_USER_NO)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.INSERT_USER_NO)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.INSERT_LOGON_NO)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.INSERT_LOGON_NO)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UPDATE_TIME)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UPDATE_TIME)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UPDATE_USER_NO)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UPDATE_USER_NO)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UPDATE_LOGON_NO)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UPDATE_LOGON_NO)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FROM_USER_NO)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FROM_USER_NO)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.MSG_SUBJECT)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.MSG_SUBJECT)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.MSG_BODY)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.MSG_BODY)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.IS_FOR_ALL)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IS_FOR_ALL)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.IS_REPLY_ALLOW)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IS_REPLY_ALLOW)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.TRN_MSG2.LAST_ACTION)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TRN_MSG2.LAST_ACTION)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.IS_REPLY)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IS_REPLY)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

OG_SLN/Views/Msg/Details.cshtml
@model OG_SLN.TRN_MSG

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>TRN_MSG</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LAST_ACTION)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LAST_ACTION)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LAST_ACTION_TIME)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LAST_ACTION_TIME)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LAST_ACTION_USER_NO)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LAST_ACTION_USER_NO)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LAST_ACTION_LOGON_NO)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LAST_ACTION_LOGON_NO)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.INSERT_TIME)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.INSERT_TIME)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.INSERT_USER_NO)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.INSERT_USER_NO)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.INSERT_LOGON_NO)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.INSERT_LOGON_NO)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UPDATE_TIME)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UPDATE_TIME)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UPDATE_USER_NO)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UPDATE_USER_NO)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UPDATE_LOGON_NO)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UPDATE_LOGON_NO)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FROM_USER_NO)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FROM_USER_NO)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.MSG_SUBJECT)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.MSG_SUBJECT)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.MSG_BODY)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.MSG_BODY)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.IS_FOR_ALL)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IS_FOR_ALL)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.IS_REPLY_ALLOW)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IS_REPLY_ALLOW)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.TRN_MSG2.LAST_ACTION)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TRN_MSG2.LAST_ACTION)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.IS_REPLY)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IS_REPLY)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.MSG_NO }) |
    @Html.ActionLink("Back to List", "Index")
</p>

OG_SLN/Views/Msg/Index.cshtml
@*@model IEnumerable<OG_SLN.TRN_MSG>*@
@model PagedList.IPagedList<OG_SLN.TRN_MSG>

@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@{Html.RenderPartial("_MessageSearchPartial");}
<p>
    @Html.ActionLink("Create New", "Create")
</p>
     <div class="row-fluid">
      <div class="col-8 marRight_2">
        <div class="table-responsive">
                <table class="table table-responsive table-bordered table-hover tabWidth">
                    <tr class="success">

                        <th>
                            @*@Html.DisplayNameFor(model => model.MSG_SUBJECT)*@
                            Subject
                        </th>
                        <th>
                            @*@Html.DisplayNameFor(model => model.MSG_BODY)*@
                            Body
                        </th>
                        <th>
                            @*@Html.DisplayNameFor(model => model.IS_FOR_ALL)*@
                            Created
                        </th>

                        <th></th>
                    </tr>

                @foreach (var item in Model) {
                    <tr>

                        <td>
                            @Html.DisplayFor(modelItem => item.MSG_SUBJECT)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.MSG_BODY)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.INSERT_TIME)
                        </td>

                        <td>
                            @*@Html.ActionLink("Edit", "Edit", new { id=item.MSG_NO }) |*@
                            @Html.ActionLink("Details", "Details", new { id=item.MSG_NO }) 
                            @*@Html.ActionLink("Delete", "Delete", new { id=item.MSG_NO })*@
                        </td>
                    </tr>
                }

                </table>
                </div>
        </div>
    </div>

<div id='Paging' style="text-align:center">
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
    of @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
</div>

OG_SLN/Views/Msg/_MessageSearchPartial.cshtml
@{

    string datefrom = DateTime.Today.AddMonths(-1).ToString("yyyy-MM-dd");
    string dateto = DateTime.Today.ToString("yyyy-MM-dd");

    OG_SLN.Models.MessageSearchViewModel searchModel = ViewBag.Search_Message_Model
        as OG_SLN.Models.MessageSearchViewModel;
    if(searchModel != null)
    {
        if(searchModel.Search_Date_From.HasValue)
        {
            datefrom = searchModel.Search_Date_From.Value.ToString("yyyy-MM-dd");
        }
        if (searchModel.Search_Date_From.HasValue)
        {
            dateto = searchModel.Search_Date_To.Value.ToString("yyyy-MM-dd");
        }
    }
}

@using(Html.BeginForm("Index", "Msg", FormMethod.Get)) {
    
    <div class="table-responsive">
        <table class="table-responsive  tabWidth">
            <tbody>

                    <tr>
                        <td class="adminLef_col">Entry Date From:</td>
                        <td class="td_1 adminRight_col">
                            @Html.TextBox("Search_Date_From", datefrom, new { @class = "dateclass form-control" })
                        </td>
                        <td class="midWidth"></td>
                        <td class="adminLef_col">Entry Date To:</td>
                        <td class="td_1 adminRight_col">
                            @Html.TextBox("Search_Date_To", dateto, new { @class = "dateclass  form-control" })
                        </td>
                    </tr>
                    <tr>
                        <td colspan="6">&nbsp;</td>
                    </tr>
                    <tr>
                        <td colspan="6" style="text-align:center;">
                             <input class="btn btn-success" type="submit" name="Search" id="Search" value="Search">
                        </td>
                    </tr>
               </tbody>
        </table>
    </div>
}