OG_SLN/Controllers/PublishController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Objects;
using System.Web.UI.WebControls;
using System.IO;
using System.Web.UI;
using System.Data;
using System.Collections;
using System.Text;
using System.Data.Objects.SqlClient;


using OG_SLN.Models;
using OG_SLN.Utils;

namespace OG_SLN.Controllers
{
    public class PublishController : Controller
    {
        private OGDBEntities db = new OGDBEntities();
        private object tr;

        public ActionResult Index()
        {
            decimal? USER_NO = Session["sess_USER_NO"] as decimal?;

            DcrPublishSearchModel searchModel = new DcrPublishSearchModel();


            //searchModel = ViewBag.Search_DcrPublish_Model as DcrPublishSearchModel;


            if (!string.IsNullOrEmpty(Request.QueryString["Search_User"]))
            {
                searchModel.Search_User = decimal.Parse(Request.QueryString["Search_User"]);
            }


            if (!string.IsNullOrEmpty(Request.QueryString["Search_Date_From"]))
            {
                searchModel.Search_Date_From = DateTime.Parse(Request.QueryString["Search_Date_From"]);
            }

            if (!string.IsNullOrEmpty(Request.QueryString["Search_Date_To"]))
            {
                searchModel.Search_Date_To = DateTime.Parse(Request.QueryString["Search_Date_To"]);
            }

            if (!string.IsNullOrEmpty(Request.QueryString["Search_pubno"]))
            {
                searchModel.Search_pubno = decimal.Parse(Request.QueryString["Search_pubno"]);
            }


            //DcrPublishSearchModel searchModel = ViewBag.Search_DcrPublish_Model;

            // searchModel = ViewBag.Search_DcrPublish_Model; 

            ViewBag.Search_DcrPublish_Model = searchModel;


            List<DCR_PUB_MASTER_GET_Result> publish_list =
            db.DCR_PUB_MASTER_GET(searchModel.Search_User, USER_NO,
            searchModel.Search_pubno, searchModel.Search_Date_From, searchModel.Search_Date_To).ToList();


            // List<TRN_USER_PUBLISH> user_pub = db.TRN_USER_PUBLISH(searchModel.Search_pubno,null,null,null);

            ViewBag.Puball_Count = publish_list.Count;



            return View(publish_list);

        }


        public ActionResult DcrPrint()
        {
            DcrPublishSearchModel searchModel = new DcrPublishSearchModel();
            DcrPublishViewModel dcrPublishModel = new DcrPublishViewModel();

            decimal? USER_NO = Session["sess_USER_NO"] as decimal?;


            //string path = Path.GetTempFileName();// file implementation with temp file in system
            //string path = @"d:\test\MyTest.txt";

            //creating file in a specified directory 

            string publish_export_url = System.Configuration.ConfigurationManager.AppSettings["PUBLISH_EXPORT_URL"];


            string Search_User = Request.QueryString["Search_User"];

            searchModel.Search_pubno = decimal.Parse(Request.QueryString["Search_pubno"]);



            string[] user_dcr = Search_User.Split(new string[] { "," }, StringSplitOptions.RemoveEmptyEntries);

            string directory_path = publish_export_url + "\\" + searchModel.Search_pubno;

            if (user_dcr.Length > 0)
            {

                if (!System.IO.Directory.Exists(directory_path))
                {
                    System.IO.Directory.CreateDirectory(directory_path);
                }
            }

            TRN_USER_PUBLISH user_publish = db.TRN_USER_PUBLISH.Where(q=>q.PUBLISH_NO ==searchModel.Search_pubno).FirstOrDefault();

            searchModel.Search_Date_From = user_publish.TRN_DATE_FROM;

            searchModel.Search_Date_To = user_publish.TRN_DATE_TO;
            

            string content = "";

            foreach (string user in user_dcr)
            {
                decimal user_no = decimal.Parse(user);
                SEC_USERS sec_user = db.SEC_USERS.Where(u => u.USER_NO == user_no).FirstOrDefault();

                string path = directory_path + "\\" + searchModel.Search_pubno + "_" + sec_user.USER_NAME + ".html";

                if (!System.IO.File.Exists(path))
                {
                    List<DCR_PUB_EXP_GET_Result> expense =
                        db.DCR_PUB_EXP_GET(user_no, null,
                            searchModel.Search_Date_From, searchModel.Search_Date_To, 1).ToList();

                    content = "<html><title>DCR Publish Report</title><body>";
                    //content += "<table>";

                    content += "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"font-size:13px\"><tr>";
                    content += "<td colspan=\"9\" style=\"text-align:center;  border:solid 1px #e4e4e4;\"> <h4>DCR Top Sheet</h4>";

                    content += "<b>Publish No. : " + searchModel.Search_pubno + "<br />";
                    content += "User Full Name : " + sec_user.USER_FULL_NAME + "<br />";

                    content += "Contact : " + sec_user.USER_MOBILE + "<br />";

                    content += "User Name : " + sec_user.USER_NAME + "<br />";

                    content += "Date From : " + searchModel.Search_Date_From.Value.ToString("yyyy-MM-dd") + " Date To : " + searchModel.Search_Date_To.Value.ToString("yyyy-MM-dd");

                    content += "</b></td></tr>";

                    content += "\n<tr><th style=\"text-align:center; border:solid 1px #e4e4e4;\">Date</th><th style=\"text-align:center; border:solid 1px #e4e4e4;\">T.A.</th><th class=\"right\"> T.Entertainment  </th>  <th class=\"right\">P.B.</th><th class=\"right\"> D.A. </th><th class=\"right\"> Other</th><th style=\"text-align:center; border:solid 1px #e4e4e4;\">Total </th> </tr>";

                    int ta = 0;
                    int te = 0;
                    int pb = 0;
                    int da = 0;
                    int other = 0;
                    int total_exp = 0;

                    int total_final = 0;

                    foreach (var exp in expense)
                    {

                        ta += (int)exp.TA_AMT;
                        te += (int)exp.TE_AMT;
                        pb += (int)exp.PB_AMT;
                        da += (int)exp.DA_AMT;
                        other += (int)exp.OB_AMT;

                        total_exp = (int)exp.TA_AMT + (int)exp.TE_AMT + (int)exp.PB_AMT + (int)exp.DA_AMT + (int)exp.OB_AMT;
                        content += "\n<tr><td  style=\"text-align:center; border:solid 1px #e4e4e4; border-top:none;\">" + exp.DT.Value.ToString("yyyy-MM-dd") + "</td><td style=\"text-align:center; border:solid 1px #e4e4e4;\">" + exp.TA_AMT + " </td><td style=\"text-align:center; border:solid 1px #e4e4e4;\">" + exp.TE_AMT + "</td><td style=\"text-align:center; border:solid 1px #e4e4e4;\">" + exp.PB_AMT + "</td><td style=\"text-align:center; border:solid 1px #e4e4e4;\">" + exp.DA_AMT + "</td><td style=\"text-align:center; border:solid 1px #e4e4e4;\">" + exp.OB_AMT + "</td> <td style=\"text-align:center; border:solid 1px #e4e4e4;\"> " + total_exp + "</td> </tr>";

                    }

                    total_final = ta + te + pb + da + other;
                    content += "<tr style=\"font-weight:bold\"><td style=\"text-align:center; border:solid 1px #e4e4e4; border-top:none;\">Total DCR Bill</td><td style=\" font-weight:bold; text-align:center; border:solid 1px #e4e4e4; border-left:none;\"> " + String.Format("{0:#,###0}", ta) + " <td style=\" font-weight:bold; text-align:center; border:solid 1px #e4e4e4; border-left:none;\">" + String.Format("{0:#,###0}", te) + "</td><td style=\" font-weight:bold; text-align:center; border:solid 1px #e4e4e4; border-left:none;\">" + String.Format("{0:#,###0}", pb) + "</td><td style=\" font-weight:bold; text-align:center; border:solid 1px #e4e4e4; border-left:none;\">" + String.Format("{0:#,###0}", da) + "</td> <td style=\" font-weight:bold; text-align:center; border:solid 1px #e4e4e4; border-left:none;\">" + String.Format("{0:#,###0}", other) + "</td><td style=\" font-weight:bold; text-align:center; border:solid 1px #e4e4e4; border-left:none;\">" + String.Format("{0:#,###0}", total_final) + "</td></tr>";

                    content += "</table>";

                    List<DCR_PUB_SPECIMEN_GET_Result> specimen =
                        db.DCR_PUB_SPECIMEN_GET(user_no, null,
                            searchModel.Search_Date_From, searchModel.Search_Date_To, 1).ToList();


                    content += "<table  class =\"page-break\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"font-size:13px; margin-top:20px; border-width:5px;border-color:Black;\">";
                    content += "<td colspan=\"5\"  style=\"text-align:center;  border:solid 1px #e4e4e4;\"><h4> Specimen Report</h4></td>";


                    content += "\n <tr><th>SL No. </th><th> Specimen Code </th><th>Specimen Name (Eng) </th><th>Specimen Name (Bng) </th><th>Quantity</th></tr>";


                    int sl_no = 1;

                    int total = 0;

                    foreach (var spec in specimen)
                    {
                        content += "\n<tr> <td  style=\"text-align:center;  border:solid 1px #e4e4e4;  border-top:none;\">" + sl_no++ + "</td>   <td  style=\"text-align:center;  border:solid 1px #e4e4e4;  border-top:none;\">" + spec.SPECIMEN_CODE + "</td><td  style=\"text-align:center;  border:solid 1px #e4e4e4;  border-top:none;\">" + spec.SPECIMEN_NAME + "</td><td  style=\"text-align:center;  border:solid 1px #e4e4e4;  border-top:none;\">" + spec.SPECIMEN_NAME_BNG + "</td><td  style=\"text-align:center;  border:solid 1px #e4e4e4;  border-top:none;\">" + spec.QTY + "</td></tr>";

                        total += (int)spec.QTY;
                    }

                    content += "<tr style=\"font-weight:bold\">";

OG_SLN/Views/Publish/AccountsPanel.cshtml
@using OG_SLN.Models
@model List<OG_SLN.DCR_PUB_ACCOUNTS_GET_Result>
@{
    Layout = "../Shared/_Layout.cshtml";
    ViewBag.Title = "AccountsPanel";
    int serialno = 1;
}
<h2>
    Accounts Manager Panel</h2>
<script type="text/javascript">
    $(document).ready(function () {
        $('#Filter_Type').val('A');

        $('.pubselect').live('click', function () {
            $('#Search_pubno').val($(this).attr('pub-no'));

            var frm = $('form');
            var url = $(frm).attr('action');
            var data = $(frm).serialize();

            $.post(url, data, function (res) {
                $('#div_display').html(res);
            });
            return false;
        });

        $('#disburse').live('click', function () {
            if ($('#comment').val() == '') {
                alert("Please put your comments !!!");
                return;
            }

            var data = {
                'Comments': $('#comment').val(),
                'PUBLISH_NO': $('#Search_pubno').val()
            };

            $.post("/Publish/DcrDoDisburse", data, function (res) {
                console.log(res);
            });
        });
    });
</script>
<div id="div_search">
    @{Html.RenderPartial("_PublishListSearchPartial", new ViewDataDictionary { {"Filter_Type", "A"}});}
</div>
<div id="div_display">
</div>

OG_SLN/Views/Publish/DcrUserPublish.cshtml
@model List<OG_SLN.DCR_PUB_PUBLISH_LIST_GET_Result>
@using OG_SLN.Models
@using OG_SLN.Helpers
@{
    ViewBag.Title = "DcrUserPublish";
}
<h2>
    DcrUserPublish</h2>

<div class="row">
    <div class="table-responsive">
        <table class="table table-bordered table-hover tabWidth">
            <tr class="success">
                <th>
                    Publish No.
                </th>
                <th>
                    User No.
                </th>
                <th>
                    Publish Date
                </th>
            </tr>
        </table>
    </div>
</div>

<table>
@foreach (var item in Model)
{
    <tr>
        <td>
            <a class="aclkn" href="#">@item.PUBLISH_NO
                @{item.PUBLISH_NO = (int)item.PUBLISH_NO;  }
            </a>
            <input name= "Search_pubno"  class="pubcheck" value="@item.PUBLISH_NO"/><h3>
            </h3>
        </td>
        <td>
            @item.USER_NO
            @{item.USER_NO = (int)item.USER_NO;}
            <input type = "hidden" value="@item.USER_NO"/>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PUBLISH_DATE)
        </td>
    </tr>
     
}
</table> 

OG_SLN/Views/Publish/Index.cshtml
@model List<OG_SLN.DCR_PUB_MASTER_GET_Result>
@using OG_SLN.Models
@using OG_SLN.Helpers
@using PagedList.Mvc;
@{
    ViewBag.Title = "Publish Panel";


    int? puball_count = ViewBag.Puball_Count;

    int total_dcr = 0;
    int total_der = 0;
    int total_sd = 0;

    int pagecount = 1;
    int dcr_amt = 0;
    int der_amt = 0;
     
}
<h2>
    Publish Panel</h2>
<style type="text/css">
    .right
    {
        text-align: right;
    }
</style>
<script src="@Url.Content("~/Scripts/autocomplete-table.js")" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function () {
        //var user_no = $(this).attr('user-no');

        $('.aclk').click(function () {
            var user_no = $(this).attr('user-no');
            var url = '@Url.Content("~")'
                + 'Reports/DcrPublish?'
                + 'Search_User=' + user_no
                + '&Search_Date_From=' + $('#Search_Date_From').val()
                + '&Search_Date_To=' + $('#Search_Date_To').val()
                + '&Search=Search';
            //console.log(url);
            w = window.open(url, '_blank');
        });

        $('#publish-print').live('click', function () {

            var users = '';
            var user_publ = $('.pubusers');
            //var checks = $('.check_list:checked');

            jQuery.each(user_publ, function () {

                var publ = $(this).attr('user-no');

                users += publ + ',';

            });

            console.log(users);

            var url = '@Url.Content("~")'
                + 'Publish/DcrPrint?'
                + 'Search_User=' + users
                + '&Search_pubno=' + $('#Search_pubno').val()
                +'&Search_Date_From=' + $('#Search_Date_From').val()
                + '&Search_Date_To=' + $('#Search_Date_To').val()
                + '&Print=N&Search=Search';

            console.log(url);
            $.get(url, function (res) {
                printWindow = window.open('', '_blank');
                printWindow.focus();
                printWindow.document.body.innerHTML = res;

            });

        });

        $('#publish').click(function () {
            var usernos = '';

            var checks = $('.check_list:checked');
            var dcr_amt = 0, der_amt = 0, sd_cnt = 0;
            jQuery.each(checks, function (i) {
                var ad = $(this).attr('user-no');
                var dcr = $(this).attr('dcr-amt');
                var der = $(this).attr('der-amt');
                var sd = $(this).attr('sd-cnt');
                dcr_amt += Number(dcr);
                der_amt += Number(der);
                sd_cnt += Number(sd);
                usernos += ad + ',';
            });

            usernos = usernos.substring(0, usernos.length - 1);
            var user_list = {
                'User_list': usernos,
                'Dcr_Amt': dcr_amt,
                'Der_Amt': der_amt,
                'Sd_Cnt': sd_cnt,
                'Search_Date_From': $("#Search_Date_From").val(),
                'Search_Date_To': $("#Search_Date_To").val()
            };
            console.log(user_list);

            $.post("/Reports/DcrDoPublish", user_list, function (res) {

                //console.log(res);
            });
        });

        // Preview implementation 

        $('.preview').click(function () {
            var user_publ = $(this).attr('user-no');
            var url = '@Url.Content("~")'
                + 'Reports/DcrPublish?'
                + 'Search_User=' + user_publ
                + '&Search_Date_From=' + $('#Search_Date_From').val()
                + '&Search_Date_To=' + $('#Search_Date_To').val()
                + '&Print=Y&Search=Search';
            $.get(url, function (res) {
                printWindow = window.open('', '_blank');
                printWindow.focus();
                printWindow.document.body.innerHTML = res;

            });
        });

        $('.pubselect').live('click', function () {
            $('#Search_pubno').val($(this).attr('pub-no'));

            var frm = $('form');
            var url = $(frm).attr('action');
            var data = $(frm).serialize();

            $.post(url, data, function (res) {
                $('#div_display').html(res);
            });
            return false;

        });

    });
</script>
<div>
    <input type="checkbox" class="check-hide" name="Show Publish Data" />
    Show Published Data</div>
<script type="text/javascript">

    $(document).ready(function () {
        $('#PublishList').hide();
        $('.check-hide').click(function () {
            if ($(this).is(':checked')) {
                $('#Search').hide();
                $('#PublishList').show();
                $('#pubdata').html('');
            }
            else {
                $('#Search').show();
                $('#PublishList').hide();
                $('#publish_list').html('');
            }
            /*
            $.post("/Publish/DcrUserPublish", function (res) {
            $('#ajax_content').html(res);
            });
            */
        });


        $('.pubcheck').live('change', function () {
            var publish_no = $(this).val();
            var user_no = $('#Search_User').val();
            console.log(publish_no);
            console.log(user_no);
            var pub_search = {

                'Search_pubno': publish_no,
                'Search_User': user_no
            };

            // $.post("/Publish/Index", pub_search, function (res) {
            //console.log(res);
            //});

            $.get("/Publish/Index", pub_search, function (res) {
                console.log(res);
            });

        });

        $('#CheckAll').change(function () {
            if ($(this).is(':checked')) {
                $('.check_list').prop('checked', true);
            }
            else {
                $('.check_list').prop('checked', false);
            }
        });

    });

    function getPublishList() {
        var frm = $('form');
        var url = '@Url.Content("~")' + 'Publish/DcrUserPublish';
        var data = $(frm).serialize();

        $.post(url, data, function (res) {
            $('#publish_list').html(res);
        });
        return false;
    }
</script>
@{

    string datefrom = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1).ToString("yyyy-MM-dd");
    string dateto = DateTime.Today.ToString("yyyy-MM-dd");
    string pubno = "";


    DcrPublishSearchModel searchModel = ViewBag.Search_DcrPublish_Model

       as DcrPublishSearchModel;


    if (searchModel != null)
    {
        if (searchModel.Search_pubno.HasValue)
        {
            pubno = searchModel.Search_pubno.ToString();
        }
        if (searchModel.Search_Date_From.HasValue)
        {
            datefrom = searchModel.Search_Date_From.Value.ToString("yyyy-MM-dd");
        }
        if (searchModel.Search_Date_To.HasValue)
        {
            dateto = searchModel.Search_Date_To.Value.ToString("yyyy-MM-dd");
        }
    }
   
}
@using (Html.BeginForm("Index", "Publish", FormMethod.Get, new { @id = "PublishForm" }))
{   
    <table>
        <tr>
            <td class="adminLef_col">
                ZM(iSearch):
            </td>
            <td class="adminRight_col">
                <input id="txtZM" type="text" class="form-control" />
                @Html.Hidden("Search_User", "")
                @Html.Hidden("Search_pubno", "")
                @Html.Hidden("Filter_Type", "P")
            </td>
        </tr>
        <tr id="datepick">
            <td>
                Entry Date From:
            </td>
            <td>
                @Html.TextBox("Search_Date_From", datefrom, new { @class = "dateclass form-control" })
            </td>
            <td class="midWidth">
                &nbsp;
            </td>
            <td class="adminLef_col">
                Entry Date To:
            </td>
            <td class="td_1 adminRight_col">
                @Html.TextBox("Search_Date_To", dateto, new { @class = "dateclass  form-control" })
            </td>
        </tr>
        <tr>
            <td style="text-align: left;">
                <input class="btn btn-success" type="submit" name="Search" id="Search" value="Search" />
                <input class="btn btn-success" type="submit" name="PublishList" id="PublishList"
                    style="display: none" value="Get Publish List" onclick="return getPublishList();" />
            </td>
        </tr>
        <tr>
            <td colspan="5" id="publish_list">
            </td>
        </tr>
        <tr>
            <td>
                <div id="ajax_content">
                </div>
            </td>
        </tr>
    </table>
        
        
    
}
<div id="div_display">
</div>
<div class="row">
    <div class="table-responsive">
        <table class="table table-bordered table-hover tabWidth" id="pubdata">
            @if (puball_count.HasValue && puball_count > 0)
            { <tr class="success">
                <td colspan="15" style="background: #EEEEEE;">
                    <input type="button" class="btn btn-info" name="publish" id="publish" value="Publish Data " />
                    
                </td>
            </tr>
            }
            <tr class="success">
                <th>
                    Serial No.
                    <input type="checkbox" name="CheckAll" id="CheckAll" />
                    Check All
                    <br />
                    
                </th>
                <th>
                    Full Name
                </th>
                <th>
                    Designation
                </th>
                <th>
                    Department
                </th>
                <th>
                    Division
                </th>
                <th>
                    Zilla
                </th>
                <th>
                    Thana
                </th>
                <th>
                    Mobile
                </th>
                <th>
                    Total DCR
                </th>
                <th>
                    Total DER
                </th>
                <th>
                    SD Count
                </th>
                <th>
                    Preview
                </th>
            </tr>
            @foreach (var item in Model)
            {
                
                <tr>
                    <td>
                   
                        <input type="checkbox" class="check_list" dcr-amt="@item.DCR_AMT" der-amt="@item.DER_AMT" sd-cnt="@item.SD_CNT" user-no="@item.USER_NO" />
                        
                      @pagecount
                        @{
                pagecount = ++pagecount; 
                 }       
                       
                    </td>
                    <td>
                        <a class="aclk"  href= "#" user-no="@item.USER_NO">@Html.DisplayFor(modelItem => item.USER_FULL_NAME)</a>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DESIG_NAME)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DEPT_NAME)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DIVISION_NAME)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ZILLA_NAME)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.THANA_NAME)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.USER_MOBILE)
                    </td>
                    <td>
                        @{dcr_amt = (int)item.DCR_AMT; total_dcr += (int)item.DCR_AMT; }

                         @Html.ThousandConvert(dcr_amt)

                    </td>
                    <td>

                     @{der_amt = (int)item.DER_AMT; total_dcr += (int)item.DCR_AMT; }

                       @Html.ThousandConvert(der_amt)
                        
                    </td>
                    <td>
                        @item.SD_CNT
                        @{item.SD_CNT = (int)item.SD_CNT; total_sd += (int)item.SD_CNT; }
                    </td>
                    <td>
                        <input user-no="@item.USER_NO" type="button" class="btn btn-info preview" name="preview" value="Preview" />
                    </td>
                </tr>
            }
            <tr style="font-weight: bold">
                <td colspan="8" style="text-align: center; border: solid 1px #e4e4e4; border-top: none;">
                    Total DCR Bill
                </td>
                @*<td>@total_dcr</td>
                <td>@total_der</td>
                <td>@total_sd</td>
                *@
                <td class="tdclass right">@Html.ThousandConvert(total_dcr)
                </td>
                <td class="tdclass right">@Html.ThousandConvert(total_der)
                </td>
                <td class="tdclass right">@total_sd
                </td>
                <td></td>
            </tr>
        </table>
    </div>
</div>

OG_SLN/Views/Publish/SalesPanel.cshtml
@model List<OG_SLN.DCR_PUB_SALES_GET_Result>
@using OG_SLN.Models
@using OG_SLN.Helpers
@{
    ViewBag.Title = "SalesPanel";

    int serial_num = 1;
}
<h2>
    Sales Manager Panel</h2>
<script type="text/javascript">
    $(document).ready(function () {
        $('#Filter_Type').val('S');

        $('.pubselect').live('click', function () {
            $('#Search_pubno').val($(this).attr('pub-no'));

            var frm = $('form');
            var url = $(frm).attr('action');
            var data = $(frm).serialize();

            $.post(url, data, function (res) {
                $('#div_display').html(res);
            });
            return false;

        });

        $('.html-down').live('click', function () {

            var user_no = $(this).attr('search-user');
            var pub_no = $(this).attr('pub-no');

            var url = "/Publish/ValidateHtmlDownload?Search_User=" + user_no + "&Search_pubno=" + pub_no;



            $.ajax({ url: url,
                type: 'POST',
                success: function (data) {
                    if (data.status == 'true') {
                        window.location = '@Url.Content("~")' + "Publish/Download?Search_User=" + user_no + "&Search_pubno=" + pub_no;
                    }
                    else {
                        alert(data.message);
                    }
                }
            });

        });


        $('#confirm').live('click', function () {
            if ($('#comment').val() == '') {
                alert("Please put your comments !!!");
                return;
            }
            var users = $('.aclk');
            var usernos = '';

            jQuery.each(users, function (i) {
                var ad = $(this).attr('user-no');
                usernos += ad + ',';
            });

            usernos = usernos.substring(0, usernos.length - 1);

            var user_list = {
                'user_not_confirmed': usernos,
                'IS_CONFIRM': 1,
                'Comments': $('#comment').val(),
                'PUBLISH_NO': $('#Search_pubno').val(),
                'Search_Date_From': $("#Search_Date_From").val(),
                'Search_Date_To': $("#Search_Date_To").val()
            };

            $.post("/Publish/DcrDoConfirm", user_list, function (res) {
                console.log(res);
            });
        });

        $('#reject').live('click', function () {
            if ($('#comment').val() == '') {
                alert("Please put your comments !!!");
                return;
            }
            var users = $('.aclk');
            var usernos = '';

            jQuery.each(users, function (i) {
                var ad = $(this).attr('user-no');
                usernos += ad + ',';
            });

            usernos = usernos.substring(0, usernos.length - 1);

            var user_list = {
                'user_not_confirmed': usernos,
                'IS_CONFIRM': 0,
                'Comments': $('#comment').val(),
                'PUBLISH_NO': $('#Search_pubno').val(),
                'Search_Date_From': $("#Search_Date_From").val(),
                'Search_Date_To': $("#Search_Date_To").val()
            };

            $.post("/Publish/DcrDoConfirm", user_list, function (res) {
                console.log(res);
            });
        });
    });
</script>
<div id="div_search">
    @{Html.RenderPartial("_PublishListSearchPartial", new ViewDataDictionary {{"Filter_Type", "S" }});}
</div>
<div id="div_display">
    @{Html.RenderPartial("_SalesPanelResult");}
</div>