OG_SLN/Controllers/DcrExpenseAllCostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OG_SLN.Models;

namespace OG_SLN.Controllers {
    public class DcrExpenseAllCostController : Controller {
        //
        // GET: /DcrExpenseAllCost/

        private OGDBEntities db = new OGDBEntities();

        protected override void Dispose(bool disposing) {
            db.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult Index() {

            ViewBag.ZonalUsers = db.SEC_USERS.Where(u => u.GEN_USER_TYPES.SHORT_NAME == "ZM");
            ViewBag.fromDate = DateTime.Now.ToString("yyyy-MM-dd");
            ViewBag.toDate = DateTime.Now.AddDays(60).ToString("yyyy-MM-dd");
            ViewBag.trnasType = db.SET_TRANSPORT_TYPE.ToList();
            ViewBag.verify_status = new SelectList(db.GEN_APPROVE_TYPE, "APPROVE_TYPE_NO", "APPROVE_TYPE");
            ViewBag.ddldivision = new SelectList(db.SET_DIVISION, "DIVISION_NO", "DIVISION_NAME");
            ViewBag.zmusers = new SelectList(db.SEC_USERS_GET_RPT_ZONAL(decimal.Parse(Session["sess_USER_NO"].ToString()),
                null, null, null).ToList(), "USER_NO", "USER_FULL_NAME");

            IList<TRN_GET_ALL_COST_Result> result = db.TRN_GET_ALL_COST(null, decimal.Parse(Session["sess_USER_NO"].ToString()),//parent
                null, null, null, DateTime.Today, DateTime.Today).ToList();

            ViewBag.result = result;


            return View();
        }

        [HttpPost]
        public ActionResult Index(DcrExpenseAllCostSearch search_obj) {
            search_obj.USER_PARENT_NO = decimal.Parse(Session["sess_USER_NO"].ToString());

            if (search_obj.USER_NO == 0) {
                search_obj.USER_NO = null;
            }
            if (search_obj.ddldivision == 0) {
                search_obj.ddldivision = null;
            }
            if (search_obj.ddlZillas == 0) {
                search_obj.ddlZillas = null;
            }
            if (search_obj.ddlThanas == 0) {
                search_obj.ddlThanas = null;
            }
            if (search_obj.zmusers == 0) {
                search_obj.zmusers = null;
            }

            if (search_obj.zmusers > 0) {
                search_obj.USER_NO = search_obj.zmusers;
            }


            IList<TRN_GET_ALL_COST_Result> result = db.TRN_GET_ALL_COST(search_obj.USER_NO, search_obj.USER_PARENT_NO,//parent
                search_obj.ddldivision, search_obj.ddlZillas, search_obj.ddlThanas, search_obj.DateFrom, search_obj.DateTo).ToList();

            ViewBag.result = result;

            return View("Result");
        }
    }
}

OG_SLN/Views/DcrExpenseAllCost/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script type="text/javascript">
    $(function () {

      $('#ddldivision').on('change', function () {
            $.post( "@Url.Content("~")"+"OfflineEntryMonitor/GetDDLData",{ id: $("#ddldivision").val(),type:"division"} ,
            function( data ) {
                $("#ddlZillas").html(data.zill);
                $("#ddlThanas").html(data.thana);
                $("#zmusers").html(data.zms);
                console.log(data.zms);
            });
        });
        $('#ddlZillas').on('change', function () {
            $.post( "@Url.Content("~")"+"OfflineEntryMonitor/GetDDLData",{ id: $("#ddlZillas").val(),type:"zilla"} ,
            function( data ) {
                $("#ddlThanas").html(data.thana);
                $("#zmusers").html(data.zms);
            });
        });
        $('#ddlThanas').on('change', function () {
            $.post( "@Url.Content("~")"+"OfflineEntryMonitor/GetDDLData",{ id: $("#ddlZillas").val(),type:"thana"} ,
            function( data ) {
                $("#zmusers").html(data.zms);
            });
        });
    });
</script>

<script type="text/javascript">
    function do_search() {
        var frm = $('form');
        var url = $(frm).attr('action');
        var data = $(frm).serialize();

        $.post(url, data, function (res) {
            $('#div_result').html(res);
        });

        return false;
    }

</script>


<h2>Index</h2>

<div id="div_search">
    @{Html.RenderPartial("SearchEntry");}
</div>
<div id="div_result">
    @{Html.RenderPartial("Result");}
</div>

OG_SLN/Views/DcrExpenseAllCost/Result.cshtml
@using OG_SLN.Helpers
@{
    Layout = null;

    List<OG_SLN.TRN_GET_ALL_COST_Result> result = ViewBag.result as List<OG_SLN.TRN_GET_ALL_COST_Result>;

    OG_SLN.TRN_GET_ALL_COST_Result item = result.FirstOrDefault();

    decimal total_all_cost = 0;
    decimal total_approve_cost = 0;

    decimal all_fare_amt = item.ALL_FARE_AMT == null ? 0 : item.ALL_FARE_AMT.Value;
    decimal all_exp_amt = item.ALL_EXP_AMT == null ? 0 : item.ALL_EXP_AMT.Value;
    decimal approve_fare_amt = item.APPROVE_FARE_AMT == null ? 0 : item.APPROVE_FARE_AMT.Value;
    decimal approve_exp_amt = item.APPROVE_EXP_AMT == null ? 0 : item.APPROVE_EXP_AMT.Value;
    
    if (item != null) {
        total_all_cost = (item.ALL_FARE_AMT == null ? 0 : item.ALL_FARE_AMT.Value) + (item.ALL_EXP_AMT == null ? 0 : item.ALL_EXP_AMT.Value);
        total_approve_cost = (item.APPROVE_FARE_AMT == null ? 0 : item.APPROVE_FARE_AMT.Value) + (item.APPROVE_EXP_AMT == null ? 0 : item.APPROVE_EXP_AMT.Value);
    }
}
<table class="tabWidth" style="font-weight:bold;text-align:right;">
    <tr>
        <td class="adminLef_col"></td>
        <td class="adminLef_col">DCR</td>
        <td class="adminLef_col">Expense</td>
        <td class="adminLef_col">Total</td>
    </tr>
    <tr>
        <td class="adminLef_col">ZM Entry</td>
        <td class="adminLef_col">@Html.ThousandConvert((int)all_fare_amt)</td>
        <td class="adminLef_col">@Html.ThousandConvert((int)all_exp_amt)</td>
        <td class="adminLef_col">@Html.ThousandConvert((int)total_all_cost)</td>
    </tr>
    <tr>
        <td class="adminLef_col">Approved</td>
        <td class="adminLef_col">@Html.ThousandConvert((int)approve_fare_amt)</td>
        <td class="adminLef_col">@Html.ThousandConvert((int)approve_exp_amt)</td>
        <td class="adminLef_col">@Html.ThousandConvert((int)total_approve_cost)</td>
    </tr>
</table>

OG_SLN/Views/DcrExpenseAllCost/SearchEntry.cshtml
@using OG_SLN.Helpers
@{
    Layout = null;
}
@*@using (Html.BeginForm(ViewContext.RouteData.GetRequiredString("action"), ViewContext.RouteData.GetRequiredString("Controller"), FormMethod.Get, new { @class = "form-horizontal" }))*@
@using (Html.BeginForm("Index", "DcrExpenseAllCost", FormMethod.Post))
{
    <table class="tabWidth">
        <tbody>
            <tr>
                <td class="adminLef_col">
                    ZM(iSearch):
                </td>
                <td>
                    <input id="txtZM" type="text" class="form-control" />
                    @Html.Hidden("USER_NO", "")
                </td>
            </tr>
            <tr>
                <td>
                    Division
                </td>
                <td>
                    @Html.DropDownList("ddldivision", String.Empty)
                </td>
                <td class="midWidth">
                    &nbsp;
                </td>
                <td class="adminLef_col">
                    Zilla:
                </td>
                <td class="adminRight_col">
                    <select id="ddlZillas" name="ddlZillas">
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    Thana
                </td>
                <td>
                    <select id="ddlThanas" name="ddlThanas">
                    </select>
                </td>
                <td class="midWidth">
                    &nbsp;
                </td>
                <td class="adminLef_col">
                    ZM:
                </td>
                <td class="adminRight_col">
                    @Html.DropDownList("zmusers", String.Empty)
                </td>
            </tr>
            <tr>
                <td class="adminLef_col">
                    DCR Date From :
                </td>
                <td class="adminRight_col">
                    <input id="DateFrom" name="DateFrom" 
                     value="@DateTime.Today.ToString("yyyy-MM-dd")" 
                                 class="form-control datesinspec"
                     type="text" />
                </td>
                <td class="midWidth">
                    &nbsp;
                </td>
                <td class="adminLef_col">
                    DCR Date To :
                </td>
                <td class="adminRight_col">
                    <input id="DateTo" name="DateTo" 
                    value="@DateTime.Today.ToString("yyyy-MM-dd")"
                    class="form-control datesinspec"
                     type="text" />
                </td>
            </tr>
            <tr>
                <td>
                    <div class="btn-group btn-group-sm">
                        <input id="Submit1" class="btn btn-success" type="submit" value="Search" onclick="return do_search()" />
                        <input id="btnReset" class="btn btn-warning" type="reset" value="Reset" />
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
}